### ISSUE TITLE
Ubuntu uses nodejs but typescript-tools expects node

### ISSUE THREAD

**Issue by aikeru** [clausreinke/typescript-tools.vim#3]
In Ubuntu, unfortunately, node is installed as /usr/bin/nodejs, but typescript-tools expects /usr/bin/node.

Is it possible to check for the presence of "nodejs" or otherwise account for this? That way people who aren't using a symlink or something for node can use this plugin without errors. :)

Thanks!

**Comment by clausreinke** [comment]
1. The vim plugin has no mention of node:-)
2. typescript-tools, in bin/tss, has the standard "/usr/bin/env  node"
3. The various ways to fix non-standard ubuntu nodejs seem to involve symlinks. Does any of your other js commandline tools without them?

Having said that, you can set g:TSS in your vimrc to make the vim plugin invoke tss via nodejs. I'm not at my pc, but something like

```
let g:TSS=["nodejs","<path to tss.js>"]
```

**Comment by clausreinke** [comment]
For reference:

[CTTE #614907] Resolution of node/nodejs conflict
https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html

**Comment by aikeru** [comment]
Maybe I should have opened this issue on typescript-tools instead of typescript-tools.vim. Sorry about that. I only noticed the issue when I tried to use TSS, which was in vim. With symlink it works great and it's a fantastic plugin! :)

Anything depending on "node" doesn't work in ubuntu without symlink. I don't think it's good practice on debian based distros at least to expect "node" to be there.

Should I open an issue on typescript-tools?
Also, if you prefer not to change it for debian-based sake I understand, but could you at very least make a note in installation that gives a hint about this?

**Comment by clausreinke** [comment]
Since there is a vim-side workaround (see above), there is no need to open another issue. Will have to think about a FAQ section somewhere.
If the workaround works for you, just close this issue.

**Comment by aikeru** [comment]
Gotcha. I'll try the workaround and report back! :)

**Comment by aikeru** [comment]
Sorry I never got back to you. Thanks for including the note in the readme concerning Ubuntu! :)
