### ISSUE TITLE
A way to provide --module flag

### ISSUE THREAD

**Issue by lazdmx** [clausreinke/typescript-tools.vim#4]
Is there any way to provide `--module, --project` flags with `TSSstarthere` command?

**Comment by clausreinke** [comment]
Sure. You can use `g:TSS` (defaults to `['tss']`, change to `let g:TSS = ['tss','--module','commonjs']`) or you can use a [tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) file for your project, or you can pass your options and files to `:TSSstart`.

NOTE to self: improve documentation before closing this!-)
