### ISSUE TITLE
Do not save .js files in the project directory

### ISSUE THREAD

**Issue by hippich** [clausreinke/typescript-tools.vim#5]
By default it seems this plugin will compile .ts file into .js in the same folder. How I can either disable saving .js file or redirect these files to different folder? (like /tmp)

**Comment by clausreinke** [comment]
? Neither `typescript-tools.vim` nor the underlying `typescript-tools` do any compilation (yet).

**Comment by hippich** [comment]
Uh, sorry about that. It was Syntastic plugin doing it.
