### ISSUE TITLE
What do I put in this line "set rtp+=<your_path_here>/typescript-tools.vim/"

### ISSUE THREAD

**Issue by wbeyda** [clausreinke/typescript-tools.vim#8]
can you post an example or something not sure what rtp and path are

**Comment by clausreinke** [comment]
`rtp` is vim's `runtimepath` - one nice thing about vim: it has built in help, so you can just type `:help rtp` to get more information. `<your_path_here>` would be the path to where you installed `typescript-tools.vim`. 

Btw, installation is now slightly simpler, if you are using a plugin manager like [vim-plug](https://github.com/junegunn/vim-plug). See the updated `README.md`.
